name: 'Check translation completeness'
on: 
  push: 
    branches:
      - '*'
permissions: write-all

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Complex-Industry-team/check-translations-ts@main
        with: 
          ignored-keys: draft_complex_industri_maincategory_title draft_industry_budget00_title
