name: 'Check translation completeness'
on: [push, pull_request]

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Complex-Industry-team/check-translations@main